// console.log("welcome");
// let x= 8;
// let y =9;
// let a =x+y;
//  a =x-y;
//  a =x*y;
//  a =x/y;
//  // Exploring the math Objects
 let a = Math;
 a = Math.E;
 a = Math.PI;
 a = Math.ceil(3.4);
 a = Math.floor(3.4);
 a = Math.round(3.4);
 a = Math.sqrt(3.4);
 a = Math.abs(3.4);
 a = Math.pow(3,2);
 a = Math.min(1,2,3,4);
 a = Math.max(1,2,3,4);
 a = 100*Math.random();
 a = 50+(100-50)*Math.random();
 a = Math.ceil(50+(100-50)*Math.random());
console.log(a);